[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
sqlx = { workspace = true }
uuid = { workspace = true }
time = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
async-trait.workspace = true
